---
- name: Configure dump settings
  hosts: all
  gather_facts: false
  become: true
  remote_user: ost

#        state=dict(type='str', required=False, choices=['present', 'info'], default='info'),
#        primary=dict(type='path', required=False),
#        secondary=dict(type='path', required=False),
#        permanent=dict(type='bool', required=False),
#        copy_directory=dict(type='path', required=False),
#        forced_copy_flag=dict(type='bool', required=False),
#        always_allow_dump=dict(type='bool', required=False),
#        nx_gzip=dict(type='bool', required=False),
#        dump_type=dict(type='str', required=False, choices=['traditional', 'fw-assisted']),
#        dump_mode=dict(type='str', required=False, choices=['disallow', 'allow', 'allow_kernel', 'require_kernel', 'allow_full', 'require_full'])


  tasks:
   - name: just a test
     ansible.builtin.shell:
       cmd: sleep 1
     register: out
     tags: tt

   - name: print before output
     ansible.builtin.debug:
       var: out
     tags: tt

   - name: configure sysdump
     sysdumpdev:
       #state: info
       nx_gzip: False
       primary: /dev/dump0
       secondary: /dev/dump1
       permanent: True
       copy_directory: /var/adm/ras
       forced_copy_flag: True
       always_allow_dump: False
       #dump_type: traditional
       dump_type: fw-assisted
       dump_mode: allow_kernel
       #dump_mode: disallow
     register: dout
     tags: dump

   - name: print after output
     ansible.builtin.debug:
       var: dout
     tags: dump
#copy_directory=/var/adm/ras forced_copy_flag=False dump_type=fw-assisted dump_mode=disallow'

...
